componentScriptContent: 
  - xmlizable: 
    - ‚Üëclassname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      ‚Üí: |
        /*Begin_c8o_AppImport*/
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        /* Uncomment the following lines to enable the i18n feature.
                         * You should add a json per language in the assets/i18n folder. */
                        translate.setDefaultLang('en');
                        translate.use(translate.getBrowserLang());
                        
                        /* Uncomment the following lines to enable the custom status bar color. */
                        // statusBar.overlaysWebView(false);
                        // statusBar.backgroundColorByHexString("#000000");
                        // statusBar.styleBlackOpaque();
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        
tplProjectName: mobilebuilder_tpl_8_0_0_ngx
‚ÜìDisplayGoogleDrivePicker [ngx.components.UIActionStack-1607693309128]: üóè mobileSharedActions/DisplayGoogleDrivePicker.yaml
‚ÜìPage [ngx.components.PageComponent-1607690643768]: üóè mobilePages/Page.yaml
‚ÜìAgGridStyle [ngx.components.UIStyle-1655222064187]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - ‚Üëclassname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        ‚Üí: |
          '.custom-header-weel {
          	background-image: url(data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7);
          	background-repeat: no-repeat;
          	background-position: center;
          }
          @import "../../node_modules/ag-grid-community/dist/styles/ag-grid.scss";
          @import "../../node_modules/ag-grid-community/dist/styles/ag-theme-balham/sass/legacy/ag-theme-balham-v22-compat.scss";
          
          
          .ag-cell-edit-input {
          	background-color: antiquewhite;
          }
          
          '